version: '3'

services:
###> doctrine/doctrine-bundle ###
  database:
    container_name: database
    image: mysql:5.7.36
    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_DATABASE: promobit
      # You should definitely change the password in production
      MYSQL_USER: promobit
      MYSQL_PASSWORD: symfony
    ports:
      - '4306:3306'
    volumes:
      - db-data:/var/lib/mysql:rw
      # You may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
      # - ./docker/db/data:/var/lib/postgresql/data:rw
###< doctrine/doctrine-bundle ###

  php:
    environment:
      - APP_ENV=dev
      - APP_SECRET=55fbe5f4ba29af842e3718e52ba614c8
      - DATABASE_URL="mysql://promobit:symfony@127.0.0.1:4306/promobit?serverVersion=5.7"
    container_name: php
    build:
      context: ./php
    ports:
      - '9000:9000'
    volumes:
      - ./app:/var/www/promobit/
    depends_on:
      - database

volumes:
###> doctrine/doctrine-bundle ###
  db-data:
###< doctrine/doctrine-bundle ###
